name: autocommit-robot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Set node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Run bash"
        run: node index.js

      - name: "Commit"
        run: |
          git config --global user.email "488548816@qq.com"
          git config --global user.name "XC0703"
          git add "pic/*"
          git commit -m "feat: save robot" || echo "Nothing to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
